### PR TITLE
Enable CORS requests

### PR DESCRIPTION
**Pull request by patrikengborg**

### CODE REVIEW

**Comment by kylestetz** [comment]
Hey thanks! I just saw your tweet. I really appreciate the PR. This is a tiny nitpick but your linter made the changeset bigger than the line you're attempting to add... would you mind fixing up the commit so that it only adds the one line? And my apologies for the way the repo is set up, I built this a long time ago before I started incorporating a linter into my projects.

**Comment by patrikengborg** [comment]
No worries, I know what it's like dealing with old buried projects 😄 But I really like what you've done here, haven't found anything close to it for generating dummy texts, it's just old boring lorem ipsum everywhere. So I wanted to contribute in some way.

Updated PR coming soon. Thanks!

**Comment by patrikengborg** [comment]
Fixed! Hope it's ok now.

**Comment by kylestetz** [comment]
Perfect! And thank you, I'm glad you like it. If you ever want to make your own ipsum generator I also open sourced the tool that powers metaphorpsum: https://github.com/kylestetz/Sentencer

Hopefully I can deploy this on my server! It's been a while 😃

**Comment by kylestetz** [comment]
Hmmm unfortunately my VPS is not in a good state. Sorry, I will attempt to fix it soon but you might not see this update on the site for a bit :(

**Comment by kylestetz** [comment]
Okay the code should be updated, let me know if it works for ya!

**Comment by patrikengborg** [comment]
Works like a charm, thanks a lot! 👍

**Pull request merged**
